### ISSUE TITLE
Display of chip configuration does not show corrent values of config node

### ISSUE THREAD

**Issue by HarterHorst** [PizzaProgram/MCP23017-PCF8574-AIO#1]
Hi,

first of all thanks for the node. I was searching long to find yours and it fits perfectly. I have two issues with the current release. 

1. The I2C address shown in the node itself is wrong. The configuration node is correct (0x38) but the node says "0x70".
2. I use a dedicated interrupt line to the raspi via GPIO pin to catch the interrupt via "rpi - gpio in" Node. When I disable the register polling by setting "Read Interval in ms" in the configuration node to 0 I get the following error message.

```
Mar 25 09:08:30 raspberrypi Node-RED[4871]: >>> Initializing PCF8574 or MPC23017 Input node >>  bitNum=0  pullUp=false  invert=true  id=04439bc07b584f49
Mar 25 09:08:30 raspberrypi Node-RED[4871]:   MCP/PCF init-Bit started... Addr=112  bitNum=0  isInput=true  pullUp=false  startAllHigh=false  LastState=-2
Mar 25 09:08:30 raspberrypi Node-RED[4871]: OK. MCP/PCF Bit-initialization finished. Bus closed.
Mar 25 09:08:30 raspberrypi Node-RED[4871]:   ...state update >>  _onOffState: 1   globalState= 1  Node_id=04439bc07b584f49
Mar 25 09:08:30 raspberrypi Node-RED[4871]:   MCP/PCF startChipTimer = 00 ms
Mar 25 09:08:30 raspberrypi Node-RED[4871]: 25 Mar 09:08:30 - [error] [MCP PCF In:04439bc07b584f49] TypeError: console.warning is not a function
```
Maybe you can have a look into the two issues.

regards
Horst

**Comment by PizzaProgram** [comment]
Hi,
 I'm glad you like it, I'm still improving it.

1. Yes, I know, I wrote about it in the "Known problems" section.
 - Can you help me with a better solution?
 - I've just started to lean about HTML scripting. (I'm a pascal programmer.)
 - Feel free to commit a change here :-)
 
2. Fixed. Uploading current state here, but not finished the new function, so will release update on NPM only in 1-2 days.

**Comment by PizzaProgram** [comment]
.. sorry, the new readme file wasn't uploaded here, so the "known problem" was old.

**Comment by PizzaProgram** [comment]
Well, I've found a quick way to finish the direct-msg-control system sooner than I've thought.
Uploaded to NPM too.

**Comment by HarterHorst** [comment]
Hi, great. Thanks for the fast reaction. Whenever I can I try to help, as soon as I have time i will try to take a look regarding the configuration issue. I will check your update asap.

**Comment by HarterHorst** [comment]
Here is my feedback to you last commit.

1. You introduced the "require("util/types");", which works fine with node v15.3.0 and later (https://nodejs.org/api/util.html#utiltypes). I had to change the line to "require("util");" for me in order to make it work with 14.19.1.
```
Mar 25 13:15:04 raspberrypi Node-RED[1349]: 25 Mar 13:15:04 - [warn] [@pizzaprogram/mcp-pcf-aio/mcp-pcf-aio] Error: Cannot find module 'util/types'
```

2. Now I am received another error.
```
Mar 25 14:03:22 raspberrypi Node-RED[1653]:   MCP/PCF > Input Force-read triggered!  msg.payload=1
Mar 25 14:03:22 raspberrypi Node-RED[1653]: 25 Mar 14:03:22 - [error] [MCP PCF In:f3e9efa753c41827] TypeError: mainChipNode.warning is not a function
```
I changes line 501 to .error which caused error messages like
```
MCP/PCF Interval (00ms) is too short for input. Setting new time = function toString() { [native code] }"
```
Sry, that I cannot provide a reasonable commit, but my node.js skills are limited. I am more on the C side.

thanks
Horst

**Comment by PizzaProgram** [comment]
Hi,

- Commented out "utiltypes". I don't know why they were there at all.
- fixed address visually at PCF (shows the half of it) 0x20 
- "warning is not a function" ...
 That's strange. I have no problem with that line. Which NR version do you  use ?

**Comment by PizzaProgram** [comment]
Published, uploaded.

**Comment by PizzaProgram** [comment]
![kép](https://user-images.githubusercontent.com/26026089/160241243-cc3a41f7-e229-40e1-802a-2d113856af91.png)
